# CMake generated Testfile for 
# Source directory: C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore
# Build directory: C:/Users/Gabriel/Documents/qt_lab/szpital_b/source/dcmcore
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(dcmcore_TestDcmCharSet "C:/Users/Gabriel/Documents/qt_lab/szpital_b/target/bin/dcmcore_TestDcmCharSet")
set_tests_properties(dcmcore_TestDcmCharSet PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;28;add_test;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;15;include;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;6;include;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;0;")
add_test(dcmcore_TestDcmDictionary "C:/Users/Gabriel/Documents/qt_lab/szpital_b/target/bin/dcmcore_TestDcmDictionary")
set_tests_properties(dcmcore_TestDcmDictionary PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;28;add_test;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;15;include;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;6;include;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;0;")
add_test(dcmcore_TestDcmReader "C:/Users/Gabriel/Documents/qt_lab/szpital_b/target/bin/dcmcore_TestDcmReader")
set_tests_properties(dcmcore_TestDcmReader PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;28;add_test;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;15;include;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;6;include;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;0;")
add_test(dcmcore_TestDcmTagGroup "C:/Users/Gabriel/Documents/qt_lab/szpital_b/target/bin/dcmcore_TestDcmTagGroup")
set_tests_properties(dcmcore_TestDcmTagGroup PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;28;add_test;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;15;include;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;6;include;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;0;")
add_test(dcmcore_TestDcmTagKey "C:/Users/Gabriel/Documents/qt_lab/szpital_b/target/bin/dcmcore_TestDcmTagKey")
set_tests_properties(dcmcore_TestDcmTagKey PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;28;add_test;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;15;include;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;6;include;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;0;")
add_test(dcmcore_TestDcmTagSequence "C:/Users/Gabriel/Documents/qt_lab/szpital_b/target/bin/dcmcore_TestDcmTagSequence")
set_tests_properties(dcmcore_TestDcmTagSequence PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;28;add_test;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;15;include;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;6;include;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;0;")
add_test(dcmcore_TestDcmTagString "C:/Users/Gabriel/Documents/qt_lab/szpital_b/target/bin/dcmcore_TestDcmTagString")
set_tests_properties(dcmcore_TestDcmTagString PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;28;add_test;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;15;include;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;6;include;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;0;")
add_test(dcmcore_TestDcmTags "C:/Users/Gabriel/Documents/qt_lab/szpital_b/target/bin/dcmcore_TestDcmTags")
set_tests_properties(dcmcore_TestDcmTags PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;28;add_test;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;15;include;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;6;include;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;0;")
add_test(dcmcore_TestDcmTransferSyntax "C:/Users/Gabriel/Documents/qt_lab/szpital_b/target/bin/dcmcore_TestDcmTransferSyntax")
set_tests_properties(dcmcore_TestDcmTransferSyntax PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;28;add_test;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;15;include;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;6;include;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;0;")
add_test(dcmcore_TestDcmVr "C:/Users/Gabriel/Documents/qt_lab/szpital_b/target/bin/dcmcore_TestDcmVr")
set_tests_properties(dcmcore_TestDcmVr PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;28;add_test;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/parse_tests.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;15;include;C:/Users/Gabriel/Documents/qt_lab/szpital/cmake/build_shared_library.cmake;0;;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;6;include;C:/Users/Gabriel/Documents/qt_lab/szpital/source/dcmcore/CMakeLists.txt;0;")
